[workspace]
members = [
  "examples/solidity/bindings",
  "types",
  "rust-sdk",
  "examples/notary",
  "examples/auction-with-dispute",
  "examples/rust",
  "examples/voting/client",
  "examples/nfts",
  "examples/tokens",
  "examples/bsky/plc",
]
resolver = "2"
