[workspace]
members = [
  "examples/solidity/bindings",
  "types",
  "rust-sdk",
  "examples/notary",
  "examples/optimistic-auction",
  "examples/rust",
  "solidity-sdk/bindings",
  "examples/voting/client",
]
resolver = "2"
