[package]
name = "pod-types"
version = "0.1.0"
edition = "2021"

[lib]
name = "pod_types"
path = "src/lib.rs"

[dependencies]
alloy-consensus = { version = "0.9.2", features = ["serde", "k256"] }
alloy-primitives = { version = "^0.8.15", features = ["k256", "serde"] }
alloy-sol-types = "^0.8.15"
alloy-signer = "0.9.2"
alloy-signer-local = "0.9.2"
alloy-network = "0.9.2"
alloy-rpc-types = "0.9.2"
k256 = { version = "0.13.4"}
eth2_ssz = "0.2.0"
bls-signatures = "0.15.0"
anyhow = "1.0"
rand = "0.8.5"
bytes = "1.8.0"
sha3 = "0.11.0-pre.4"
subtle = "2.6.1"
ecdsa = "0.16.9"
rand_core = "0.6.4"
hex = { version = "0.4.3", features = ["serde"] }
serde_json = "1.0.132"
serde = { version = "1.0.214", features = ["derive"] }
jsonrpsee = { version = "0.24.8", features = ["server", "http-client", "ws-client", "macros", "client-ws-transport-tls", "tokio"] }
itertools = "0.13.0"
bincode = "1.3.3"
rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb", rev = "1cf906dc4087f06631820f13855e6b27bd21b972" }
toml = "0.8"
async-trait = "0.1.83"
tokio = { version = "1.42.0", features = ["rt", "macros"] }
futures = "0.3.31"
tokio-stream = "0.1.17"
base64 = "0.22.1"
utoipa = "5.3.1"
backoff = { version = "0.4.0", features = ["tokio"] }
tokio-util = "0.7.13"
serde-hex = "0.1.0"
bitvec = { version = "1.0.1", features = ["serde"] }
const_format = "0.2.34"
alloy-rpc-client = "0.9.2"
alloy-json-rpc = "0.9.2"
alloy-transport = "0.9.2"
revm = "19.5.0"
sha2 = "0.10.8"