[package]
name = "optimistic-auction"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "optimistic_auction"
path = "client/main.rs"

[dependencies]
pod-examples-solidity = { path = "../solidity/bindings" }
