[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "pod-sdk/=../../solidity-sdk/src/",
]
allow_paths = ["../../solidity-sdk"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
