name: Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: versions
      run: |
        cargo version
        cargo fmt --version

    - name: rustfmt check
      run: cargo fmt --check
