name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2
    - name: Versions
      run: |
        cargo version
        cargo clippy --version

    - name: Run clippy
      run: cargo clippy -- -D warnings
