name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Cache cargo dependencies
      id: cache-cargo
      uses: actions/cache@v4
      env:
        cache-name: cache-cargo-dependencies
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}

    - name: Version
      run: cargo version

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
